AllCops:
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  NewCops: enable

plugins:
  - rubocop-minitest

# Exclude test directories from metrics
Metrics:
  Exclude:
    - 'test/**/*'
    - 'examples/**/*'

# Disable problematic cops
Lint/MissingCopEnableDirective:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

# Allow multiple assertions in system tests
Minitest/MultipleAssertions:
  Exclude:
    - 'examples/**/*'