# frozen_string_literal: true

source "https://rubygems.org"

gem "capybara"
gem "selenium-webdriver"
gem "minitest"
gem "rack"
gem "puma"

# Our gem (in real usage, this would be: gem 'capybara-demo')
gem "capybara-demo", path: "../.."